
.Preface

As OGC standards have developed, the Standards Working Groups have introduced various ways to indicate the spatial limits or extents of information of interest. These limits have various names such as 'bounding box', 'bounding volume', 'extent', 'envelope' or even 'convex hull'. There appears to be no underlying conceptual model identified or defined in the OGC Abstract Topics, but in OGC standards there are a confusing variety of concrete encodings and interpretations.

The original 'bounding box' in 2D on a flat map may have been very self-explanatory, but as standards now encompass 3D, 4D, or more, dimensions, and use cases extend beyond selecting a simple area of interest to moving objects, animations, collision detection, computationally expensive visualisations requiring object pruning, and simulated, virtual and augmented realities, this specification is an attempt to ensure a sound conceptual basis and terminology are established to ensure consistency and interoperability of OGC Standards.

The lack of an agreed defined abstract concept was highlighted in the development of the OGC API Common standard.

[NOTE]
====
Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.

There are two ways to specify the Preface: "simple clause" or "full clasuse"

If the Preface does not contain subclauses, it is considered a simple preface clause. This one is entered as text after the `.Preface` label and must be placed between the AsciiDoc document attributes and the first AsciiDoc section title. It should not be give a section title of its own.

If the Preface contains subclauses, it needs to be encoded as a full preface clause. This one is recognized as a full Metanorma AsciiDoc section with te title "Preface", i.e. `== Preface`. (Simple preface content can also be encoded like full preface.) 
====


[abstract]
== Abstract

<Insert abstract here.>


[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
h| Name h| Affiliation
| Sam Meek | Helyx
| Chris Little | Met Office
...
|===


[.preface]
== Introduction

The concept of a bounding box (BBOX) to identify the bounds of an area of interest is a well-known concept in geography and geospatial systems. There are several terms used across standards that refer to similar concepts that include; bounding box, envelope, minimum bounding box, bounding shape, plus others. One of the key features of the BBOX concept is that it refers to some geographic location that encompasses a resource. With the advent of multi-dimensional data where the geograhy is one element of the dataset _scope_, it is prudent to consider a definition of a BBOX that encompasses or at least supports n-dimensional datasets. One way of understanding a dataset's bounds is via its scope and associated metadata, the concept of a dataset is moveable and at its basic level is a group of features with shared attributes or a coverage. Dataset scoping is almost up to the the data manager to decide, there do not appear to be contraints beyond sharing attributes.

This Topic presents a conceptual model for a BBOX that:

* Encompasses the current BBOX definitions.
* Extends to include n-dimensional data.
* Allows scoping and attribute definition within the model such as time, CRS, or some other measure.
* Harmonizes with concepts of geospatial metadata to make dataset FAIR (Findable, Accessible, Interoperable, Reusable).


[.preface]
== Reference notes

<Place reference notes here.>


[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====
