
.Preface

As OGC standards have developed, the Standards Working Groups have introduced various ways to indicate the spatial limits or extents of information of interest. These limits have various names such as 'bounding box', 'bounding volume', 'extent', 'envelope' or even 'convex hull'. There appears to be no underlying conceptual model identified or defined in the OGC Abstract Topics, but in OGC standards there are a confusing variety of concrete encodings and interpretations.

The original 'bounding box' in 2D on a flat map may have been very self-explanatory, but as standards now encompass 3D, 4D, or more, dimensions, and use cases extend beyond selecting a simple area of interest to moving objects, animations, collision detection, computationally expensive visualisations requiring object pruning, and simulated, virtual and augmented realities, this specification is an attempt to ensure a sound conceptual basis and terminology are established to ensure consistency and interoperability of OGC Standards.

The lack of an agreed defined abstract concept was highlighted in the development of the OGC API Common standard.

[NOTE]
====
Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.

There are two ways to specify the Preface: "simple clause" or "full clasuse"

If the Preface does not contain subclauses, it is considered a simple preface clause. This one is entered as text after the `.Preface` label and must be placed between the AsciiDoc document attributes and the first AsciiDoc section title. It should not be give a section title of its own.

If the Preface contains subclauses, it needs to be encoded as a full preface clause. This one is recognized as a full Metanorma AsciiDoc section with te title "Preface", i.e. `== Preface`. (Simple preface content can also be encoded like full preface.) 
====


[abstract]
== Abstract

<Insert abstract here.>


[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
h| Name h| Affiliation
| John Doe | Landcare Research New Zealand
...
|===


[.preface]
== Introduction

<Insert introduction here.>


[.preface]
== Reference notes

<Place reference notes here.>


[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====
