[appendix,obligation="informative"]
== OGC Standards with existing definitions [to be checked]

Not every document in the Abstract Specification has been inspected. 

* basic BBox from WMS is "lowest common denominator".

* "boundingBox" element in GML, utilised by a range of Web Service specifications.  

* CDB 2.0 will have similar issues (including 4D BBoxes).

* I3S : Has definitions for bounding volume, minimum bounding sphere, oriented bounding box: https://github.com/opengeospatial/ogc-i3s-community-standard/blob/main/format/clause_4_terms_and_definitions.adoc .

* 3D Tiles: Has definitions for bounding box (oriented bounding box), bounding  sphere, bounding region https://github.com/CesiumGS/3d-tiles/tree/main/specification#bounding-volumes . 

* OGC Filter 1.1:The <BBOX> element is defined as a convenient and more compact way of encoding the very common bounding box constraint based on the gml:Envelope geometry.

* GeoPackage:  Requirement 144: The bounding box defined by min_x, max_x, min_y, and max_y SHALL be exact so that the bounding box coordinates for individual tiles in a tile pyramid MAY be calculated from those values. All tiles present in the tile pyramid SHALL fall within this bounding box. Informative: The bounding box (min_x, min_y, max_x, max_y) provides an informative bounding box of the content. Applications may use this bounding box as the extents of a default view but there are no requirements that this bounding box be exact or represent the minimum bounding box of the content. GPKG also defines a maximum bounding box.

* Moving Features: mf:sTBoundedBy - This element regulates the spatio-temporal region where the trajectories described in the foliation exist. Times used in trajectories are described in offset time, that is, duration in seconds or minutes or hours from the time origin defined here is shown in the trajectory elements. The mf:STBoundedBy element inherits gml: BoundingShapeType, and include gml:EnvelopeWithTimePeriod [OGC 07‑036].

* GeoRSS: A bounding box defines a rectangular region. This object is often used to define the extents of a map or define a rough area of interest. A GML box is called an Envelope. It consists of an <Envelope> element with a child <lowerCorner> element and a child <upperCorner> element.

* GeoJSON: Bounding box (bbox) - A GeoJSON object MAY have a member named "bbox" to include information on the coordinate range for its Geometries, Features, or FeatureCollections.  The value of the bbox member MUST be an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point.  The axes order of a bbox follows the axes order of geometries.

* Coverages: a bounding box, in a Coverage's Domain Set, defines an n-D rectangular region, defined through bounded intervals on each of its axes. A coverage is defined by one single CRS which lists all axes (in proper order) and defines the common CRS following the mechanisms of ISO 19111. A coverage may have horizontal x/y dimensions, a height/depth dimension, and one or more time axes, as well as non-spatio-temporal axes (called "abstract" in 19123-1 and "parametric" in 19111). Examples of such abstract axes include spectral bands, geostatistical measures, proxies like pressure altitude, etc. All axes are treated the same way, not withstanding that particular domain restrictions may apply (such as not having Latitude without Longitude, or having Latitude twice). Operations in WCS and WCPS, such as subsetting and scaling, allow deriving coverages from given ones, with possibly only some of the axes retained in the resulting Coverage's CRS; similarly, domain restrictions may apply when deriving coverages.

== Non-OGC standards:
* DCMI Box as an extension to the Dublin Core metadata scheme.

* "Bounding Coordinates" in the (U.S.) FGDC metadata standard.

* "Geographic Bounding Box" in the (2003–current) ISO 19115 Metadata Standard for geographic information (ISO/TC 211). 

* In the ISO 19107 Spatial Schema (ISO/TC 211), MBR appears as the datatype GM_Envelope that is returned by the envelope() operation on the root class GM_Object.


[NOTE]
====
Place annex material in sequential order and set `obligation` attribute as "normative" (default) or "informative" according to the case.
====
